### ISSUE TITLE
[json array] Panic when buffer contains an incomplete object

### ISSUE THREAD

**Issue by glueball** [abdolence/reqwest-streams-rs#15]
If the streaming JSON contains incomplete objects, the JsonArrayCodec might panic. 

```
panicked at 'slice index starts at 1577 but ends at 975', C:\xxx\reqwest-streams-rs\src\json_array_codec.rs:57:39
```

I think the problem is in line 129 of `json_array_codec.rs`. It is

```rust
        self.json_cursor.current_offset += buf.len();
```

it should be

```rust
        self.json_cursor.current_offset = buf.len();
```

**Comment by abdolence** [comment]
I was able to reproduce the same behaviour for unit test and confirmed the fix in this PR:
https://github.com/abdolence/reqwest-streams-rs/pull/17

**Comment by glueball** [comment]
Great, abdolence, I updated to 0.3 and everything works!

Thanks for the crate, I've learned a lot of Rust and Tokio with it ;)
